package cmd
package cmd

import (
	"fmt"
	"os"
	"path/filepath"






































































































































































}	return nil	}		fmt.Println("(This was a dry-run; no actual changes were made)")	if dryRun {	fmt.Println("=== Processing complete ===")	}		fmt.Println()		fmt.Println("  ✓ Archive processed successfully")		}			fmt.Printf("    Updated torrent location: %s\n", updatedTorrent.SavePath)		if updatedTorrent != nil {		}			continue			fmt.Printf("    ERROR: Failed to verify update: %v\n", err)		if err != nil {		updatedTorrent, err := qbClient.GetTorrent(torrent.Hash)		// Verify the update		}			continue			fmt.Printf("    NOTE: RAR directory moved but torrent tracking may be broken\n")			fmt.Printf("    ERROR: Failed to update torrent location: %v\n", err)		if err := qbClient.SetLocation(torrent.Hash, newLocation); err != nil {		fmt.Printf("  Step 5: Updating qBittorrent torrent location...\n")		// Step 5: Update torrent location in qBittorrent		fmt.Println()		}			continue			fmt.Printf("    ERROR: Move failed: %v\n", err)		if err := moveMgr.MoveDirectory(rarFile.Directory, newLocation); err != nil {		}			continue			fmt.Printf("    ERROR: Move validation failed: %v\n", err)		if err := moveMgr.ValidateMoveOperation(rarFile.Directory, newLocation); err != nil {		fmt.Printf("    To:   %s\n", newLocation)		fmt.Printf("    From: %s\n", rarFile.Directory)		newLocation := filepath.Join(cfg.Paths.Zombies, filepath.Base(rarFile.Directory))		fmt.Printf("  Step 4: Relocating RAR directory to zombies...\n")		// Step 4: Relocate RAR directory		fmt.Println()		fmt.Printf("    Current location: %s\n", torrent.SavePath)		fmt.Printf("    Found torrent: %s\n", torrent.Name)		}			continue			fmt.Println()			fmt.Println("    (RAR files will remain in place)")			fmt.Printf("    WARNING: No torrent found for path: %s\n", rarFile.Directory)		if torrent == nil {		}			continue			fmt.Printf("    ERROR: Failed to query torrents: %v\n", err)		if err != nil {		torrent, err := qbClient.FindTorrentByPath(rarFile.Directory)		fmt.Printf("  Step 3: Finding torrent in qBittorrent...\n")		// Step 3: Find torrent		fmt.Println()		}			}				continue				fmt.Printf("    ERROR: Extraction failed: %v\n", err)			if err := ext.Extract(rarFile); err != nil {		} else {			fmt.Printf("    [DRY RUN] Would extract: %s\n", rarFile.Path)		if dryRun {		fmt.Printf("  Step 2: Extracting with 7z...\n")		// Step 2: Extract		fmt.Printf("Processing RAR archive %d of %d: %s\n", i+1, len(rarFiles), rarFile.BaseName)	for i, rarFile := range rarFiles {	moveMgr := mover.New(dryRun)	// Process each RAR file	fmt.Println()	}		return fmt.Errorf("failed to authenticate with qBittorrent: %w", err)	if err := qbClient.Login(); err != nil {	fmt.Println("Authenticating with qBittorrent...")	// Login to qBittorrent	}		return fmt.Errorf("failed to initialize qBittorrent client: %w", err)	if err != nil {	qbClient, err := qbittorrent.New(cfg.QBittorrent.URL, cfg.QBittorrent.Username, cfg.QBittorrent.Password)	// Initialize qBittorrent client	fmt.Println()	}		fmt.Printf("  %d. %s (in %s)\n", i+1, filepath.Base(rar.Path), filepath.Base(rar.Directory))	for i, rar := range rarFiles {	fmt.Printf("Found %d RAR archive(s):\n", len(rarFiles))	}		return nil		fmt.Println("No RAR files found in directory")	if len(rarFiles) == 0 {	}		return fmt.Errorf("failed to find RAR files: %w", err)	if err != nil {	rarFiles, err := ext.FindRARFiles()	ext := extractor.New(targetPath)	fmt.Printf("Step 1: Scanning directory for RAR files: %s\n", targetPath)	// Step 1: Find RAR files	fmt.Println("=== rarclean - RAR Extraction & qBittorrent Manager ===\n")	}		return fmt.Errorf("failed to load configuration: %w", err)	if err != nil {	cfg, err := config.Load(configPath)	// Load configurationfunc runRarclean(cmd *cobra.Command, args []string) error {}	return rootCmd.Execute()func Execute() error {}	rootCmd.MarkFlagRequired("path")	rootCmd.Flags().StringVar(&targetPath, "path", "", "Directory containing RAR files to process (required)")	rootCmd.Flags().BoolVar(&dryRun, "dry-run", false, "Show planned actions without executing")	rootCmd.Flags().StringVar(&configPath, "config", "config.json", "Path to configuration file")func init() {}	RunE: runRarclean,This maintains seeding while organizing extracted media.`,5. Updating qBittorrent's file tracking4. Moving the RAR directory to a zombies location3. Finding the associated torrent in qBittorrent2. Extracting them using 7z1. Locating RAR archives in a directory	Long: `rarclean is a CLI tool that automates the workflow of:	Short: "Automated RAR extraction and qBittorrent management for media libraries",	Use:   "rarclean",var rootCmd = &cobra.Command{)	targetPath string	dryRun     bool	configPath stringvar ()	"github.com/killakam3084/rarclean/internal/qbittorrent"	"github.com/killakam3084/rarclean/internal/mover"	"github.com/killakam3084/rarclean/internal/extractor"	"github.com/killakam3084/rarclean/internal/config"	"github.com/spf13/cobra"